import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const __filename=fileURLToPath(import.meta.url);const __dirname=path.dirname(__filename);const publicDir=path.join(__dirname,'public');const port=Number(process.env.PORT||3000);const allowedOrigin=process.env.FRONTEND_ORIGIN||'https://teamindomail.github.io';
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml'};
function corsHeaders(origin){return {'Access-Control-Allow-Origin':origin===allowedOrigin?origin:allowedOrigin,'Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Authorization,Content-Type,X-Zoho-Api-Domain','Vary':'Origin'};}
function sendJson(res,status,body){res.writeHead(status,{...corsHeaders(res.__origin||''),'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(body));}
async function serveFile(urlPath,res){const requested=urlPath==='/'?'index.html':urlPath.replace(/^\/+/, '');const filePath=path.resolve(publicDir,requested);if(!filePath.startsWith(publicDir+path.sep))return sendJson(res,403,{error:'Forbidden'});try{const data=await fs.readFile(filePath);const type=mime[path.extname(filePath).toLowerCase()]||'application/octet-stream';res.writeHead(200,{'Content-Type':type,'Cache-Control':'no-cache'});res.end(data);}catch{sendJson(res,404,{error:'Not found'});}}
function validateZohoMailDomain(value){try{const raw=String(value||'').trim().replace(/\/$/,'');const u=new URL(raw);if(u.protocol!=='https:')return null;let host=u.hostname.toLowerCase();if(host.startsWith('www.zohoapis.'))host=`mail.zoho.${host.slice('www.zohoapis.'.length)}`;else if(host.startsWith('zohoapis.'))host=`mail.zoho.${host.slice('zohoapis.'.length)}`;const allowed=new Set(['mail.zoho.com','mail.zoho.in','mail.zoho.eu','mail.zoho.com.au','mail.zoho.jp','mail.zohocloud.ca','mail.zoho.com.cn','mail.zoho.ae','mail.zoho.sa']);if(!allowed.has(host))return null;return `https://${host}`;}catch{return null;}}
async function proxyZoho(req,res,url){const token=req.headers.authorization;if(!token?.startsWith('Zoho-oauthtoken '))return sendJson(res,401,{error:'Missing Zoho authorization token'});const apiDomain=validateZohoMailDomain(req.headers['x-zoho-api-domain']);if(!apiDomain)return sendJson(res,400,{error:'Invalid Zoho Mail API domain'});const target=new URL(`${apiDomain}${url.pathname.replace('/api/zoho','')}${url.search}`);const upstream=await fetch(target,{method:req.method,headers:{Accept:'application/json',Authorization:token}});const text=await upstream.text();res.writeHead(upstream.status,{...corsHeaders(res.__origin||''),'Content-Type':upstream.headers.get('content-type')||'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(text);}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);res.__origin=req.headers.origin||'';if(req.method==='OPTIONS'){res.writeHead(204,corsHeaders(res.__origin));return res.end();}if(url.pathname==='/api/health'&&req.method==='GET')return sendJson(res,200,{ok:true,app:'IndoMail',version:'0.3.2'});if(url.pathname.startsWith('/api/zoho/')&&(req.method==='GET'||req.method==='POST'))return proxyZoho(req,res,url);if(req.method!=='GET')return sendJson(res,405,{error:'Method not allowed'});return serveFile(url.pathname,res);}catch(error){console.error('Server error:',error);return sendJson(res,500,{error:error.message||'Internal server error'});}});server.listen(port,'0.0.0.0',()=>console.log(`IndoMail running at http://localhost:${port}`));